name: Build and Run Tests on Push

on:  
  push:  
    branches:  
      - "**"  # Runs on any branch push

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest  # Change to windows-latest or macos-latest if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  
          java-version: '17'  # Adjust based on your project

      - name: Build Project (Maven)
        run: mvn clean package -DskipTests=true  # If using Maven

      # Debugging Step: List files in target directory
      - name: List Target Directory
        run: ls -lah target  # This will show if new2.jar exists

      - name: Execute Tests
        run: |
          set -e
          cd target
          echo "✅ Running Java Test..."
          java -jar new2-1.0.0-jar-with-dependencies.jar > test-output.log 2>&1 || echo "❌ Test execution failed, but continuing."

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test-Logs
          path: target/test-output.log
